version: '3'
services:
  base-spring:
    container_name: backend-spring
    image: backend-spring:1.0
    ports:
      - "8081:8081"
    volumes:
      - /etc/localtime:/etc/localtime
    environment:
        ACTIVE: ${ACTIVE}
        LOG_IMPL: ${LOG_IMPL}
        RD_HOST: ${RD_HOST}
        RD_PASSWORD: ${RD_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
        DB_PASSWORD: ${DB_PASSWORD} 
        HW_AK: ${HW_AK}
        HW_SK: ${HW_SK}
        ENABLE_RESOURCE_INIT: ${ENABLE_RESOURCE_INIT}
        WX_APP_ID: ${WX_APP_ID}
        WX_APP_SECRET: ${WX_APP_SECRET}
    restart: always
