spring:
  application:
    name: backendSpring
  profiles:
    active: ${ACTIVE:dev}
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

server:
  servlet:
    context-path: /backend

mybatis-plus:
  global-config:
    db-config:
      #      逻辑删除，删除标志
      logic-delete-value: 1
      #      逻辑删除，未删除标志
      logic-not-delete-value: 0
  type-aliases-package: com.backend.entity
  configuration:
    #    mybatis-plus日志
    log-impl: ${LOG_IMPL:org.apache.ibatis.logging.stdout.StdOutImpl}
#    #!/bin/bash
#image_name="backend-spring"
#container_name=$image_name
#tag="1.0"
#jar_name="backend-spring-0.0.1-SNAPSHOT.jar"
#yml_name="spring-compose.yml"
