server:
  port: 8081

spring:
  redis:
    host: 47.107.47.184
    # MTIzNDU2
    password: ENC(et31hW0zXucxdtnGQWBFw4vvxE8ekNOfxL9ABiIZ1kFtXNQ/gOqiT3TpjA9SE+x1)
    database: 5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    druid:
      url: jdbc:postgresql://47.107.47.184:5432/base_spring?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&yearIsDateType=false&stringtype=unspecified
      username: postgres
      # MTIzNDU2
      password: ENC(et31hW0zXucxdtnGQWBFw4vvxE8ekNOfxL9ABiIZ1kFtXNQ/gOqiT3TpjA9SE+x1)
      # 连接池配置
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      # 配置获取连接等待超时的时间
      # 开发环境尽量小，便于暴露问题，生产环境需调成3倍以上
      maxWait: 3000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 600000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: fang
        #YWRtaW4xMjM=
        login-password: ENC(jRfyAn53MGCVZbU6vfn7iRqcnnp66QGXscsQfN2kZD/3Yco/U3rhkPKk3Zd8F90g)
        allow:

logging:
  file:
    name: fang.log
    path: ./log
  level:
    root: error