spring:
  application:
    name: backendSpring
  profiles:
    active: dev
server:
  servlet:
    context-path: /fang

mybatis-plus:
  global-config:
    db-config:
      #      逻辑删除，删除标志
      logic-delete-value: 1
      #      逻辑删除，未删除标志
      logic-not-delete-value: 0
  type-aliases-package: com.fang.entity
  configuration:
    #    mybatis-plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


jasypt:
  encryptor:
    password:
