spring:
  application:
    name: backendSpring
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效

server:
  servlet:
    context-path: /backend

mybatis-plus:
  global-config:
    db-config:
      #      逻辑删除，删除标志
      logic-delete-value: 1
      #      逻辑删除，未删除标志
      logic-not-delete-value: 0
  type-aliases-package: com.backend.entity
  configuration:
    #    mybatis-plus日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

