server:
  port: 8081
#vwqetgsrthwr6tuysrgjnsrtyhsejn
spring:
  redis:
    host: ${RD_HOST:47.107.47.184}
    # MTIzNDU2
    password: ${RD_PASSWORD:654321}
    database: 5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://47.107.47.184:3306/base_spring?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&yearIsDateType=false&stringtype=unspecified&jiansuo=true&allowPublicKeyRetrieval=true
      username: ${DB_USERNAME:root}
      # 44A8B4F7C0723A4C2A12858C7DD0FEE0
      password: ${DB_PASSWORD:admin123}
      # 连接池配置
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 1
      maxActive: 20
      # 配置获取连接等待超时的时间
      # 开发环境尽量小，便于暴露问题，生产环境需调成3倍以上
      maxWait: 3000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 600000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      #useGlobalDataSourceStat: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        login-username: backend
        #YWRtaW4xMjM=
        login-password: admin123
        allow:

logging:
#  file:
#    name: backend.log
#    path: ./log
  level:
    root: info

#obs
huawei:
  obs:
    ak: ${HW_AK:VQDWIR6B5ICO8SGZNMYN}
    sk: ${HW_SK:ueZqrJZbLLBS8NJzFqJqcCLbrhJev606HSK8xmPV}
    upload:
      endPoint: obs.cn-south-1.myhuaweicloud.com
    bucketName: sport-exam
    parentDir:  xxx

application:
  security:
    base64Secret: MDVlZmQxYTdlNzc4YzQ1NzdjYWIxZTdmYTAyMmM4NGQxODFlY2JmODczZjY4YzQ2YzE3Y2IyZjFjNWMxODQxYTQ0NGJhMWQzZDBhZmZhODYyNzRjNDA5OGM2YmY5YWQyNzNiMmY3YjMxZjE2YTRjODRhNjEyZjFkZDgzYTNlMjI=
    tokenSignKey: bcdedit
    expirationTime_rememberMe: 720000000
    #两小时过期
    expirationTime_no_rememberMe: 7200000
    tokenPrefix: Bearer
    defaultPassword: 123456
  resource:
    #如果不加引号，则代码会将其读取为true or false
    enableResourceInit: ${ENABLE_RESOURCE_INIT:"no"}